# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/topuz/Documents/GEANT4/GEANT4 _Project/examples/basic/Muon/Waste_barrel"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/topuz/Documents/GEANT4/GEANT4 _Project/examples/basic/Muon/Waste_barrel"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/topuz/Documents/GEANT4/GEANT4 _Project/examples/basic/Muon/Waste_barrel/CMakeFiles" "/home/topuz/Documents/GEANT4/GEANT4 _Project/examples/basic/Muon/Waste_barrel/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/topuz/Documents/GEANT4/GEANT4 _Project/examples/basic/Muon/Waste_barrel/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Target_material

# Build rule for target.
Target_material: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Target_material
.PHONY : Target_material

# fast build rule for target.
Target_material/fast:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/build
.PHONY : Target_material/fast

Target_material.o: Target_material.cc.o

.PHONY : Target_material.o

# target to build an object file
Target_material.cc.o:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/Target_material.cc.o
.PHONY : Target_material.cc.o

Target_material.i: Target_material.cc.i

.PHONY : Target_material.i

# target to preprocess a source file
Target_material.cc.i:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/Target_material.cc.i
.PHONY : Target_material.cc.i

Target_material.s: Target_material.cc.s

.PHONY : Target_material.s

# target to generate assembly for a file
Target_material.cc.s:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/Target_material.cc.s
.PHONY : Target_material.cc.s

src/B1ActionInitialization.o: src/B1ActionInitialization.cc.o

.PHONY : src/B1ActionInitialization.o

# target to build an object file
src/B1ActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1ActionInitialization.cc.o
.PHONY : src/B1ActionInitialization.cc.o

src/B1ActionInitialization.i: src/B1ActionInitialization.cc.i

.PHONY : src/B1ActionInitialization.i

# target to preprocess a source file
src/B1ActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1ActionInitialization.cc.i
.PHONY : src/B1ActionInitialization.cc.i

src/B1ActionInitialization.s: src/B1ActionInitialization.cc.s

.PHONY : src/B1ActionInitialization.s

# target to generate assembly for a file
src/B1ActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1ActionInitialization.cc.s
.PHONY : src/B1ActionInitialization.cc.s

src/B1DetectorConstruction.o: src/B1DetectorConstruction.cc.o

.PHONY : src/B1DetectorConstruction.o

# target to build an object file
src/B1DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1DetectorConstruction.cc.o
.PHONY : src/B1DetectorConstruction.cc.o

src/B1DetectorConstruction.i: src/B1DetectorConstruction.cc.i

.PHONY : src/B1DetectorConstruction.i

# target to preprocess a source file
src/B1DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1DetectorConstruction.cc.i
.PHONY : src/B1DetectorConstruction.cc.i

src/B1DetectorConstruction.s: src/B1DetectorConstruction.cc.s

.PHONY : src/B1DetectorConstruction.s

# target to generate assembly for a file
src/B1DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1DetectorConstruction.cc.s
.PHONY : src/B1DetectorConstruction.cc.s

src/B1EventAction.o: src/B1EventAction.cc.o

.PHONY : src/B1EventAction.o

# target to build an object file
src/B1EventAction.cc.o:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1EventAction.cc.o
.PHONY : src/B1EventAction.cc.o

src/B1EventAction.i: src/B1EventAction.cc.i

.PHONY : src/B1EventAction.i

# target to preprocess a source file
src/B1EventAction.cc.i:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1EventAction.cc.i
.PHONY : src/B1EventAction.cc.i

src/B1EventAction.s: src/B1EventAction.cc.s

.PHONY : src/B1EventAction.s

# target to generate assembly for a file
src/B1EventAction.cc.s:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1EventAction.cc.s
.PHONY : src/B1EventAction.cc.s

src/B1PrimaryGeneratorAction.o: src/B1PrimaryGeneratorAction.cc.o

.PHONY : src/B1PrimaryGeneratorAction.o

# target to build an object file
src/B1PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1PrimaryGeneratorAction.cc.o
.PHONY : src/B1PrimaryGeneratorAction.cc.o

src/B1PrimaryGeneratorAction.i: src/B1PrimaryGeneratorAction.cc.i

.PHONY : src/B1PrimaryGeneratorAction.i

# target to preprocess a source file
src/B1PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1PrimaryGeneratorAction.cc.i
.PHONY : src/B1PrimaryGeneratorAction.cc.i

src/B1PrimaryGeneratorAction.s: src/B1PrimaryGeneratorAction.cc.s

.PHONY : src/B1PrimaryGeneratorAction.s

# target to generate assembly for a file
src/B1PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1PrimaryGeneratorAction.cc.s
.PHONY : src/B1PrimaryGeneratorAction.cc.s

src/B1RunAction.o: src/B1RunAction.cc.o

.PHONY : src/B1RunAction.o

# target to build an object file
src/B1RunAction.cc.o:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1RunAction.cc.o
.PHONY : src/B1RunAction.cc.o

src/B1RunAction.i: src/B1RunAction.cc.i

.PHONY : src/B1RunAction.i

# target to preprocess a source file
src/B1RunAction.cc.i:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1RunAction.cc.i
.PHONY : src/B1RunAction.cc.i

src/B1RunAction.s: src/B1RunAction.cc.s

.PHONY : src/B1RunAction.s

# target to generate assembly for a file
src/B1RunAction.cc.s:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1RunAction.cc.s
.PHONY : src/B1RunAction.cc.s

src/B1SteppingAction.o: src/B1SteppingAction.cc.o

.PHONY : src/B1SteppingAction.o

# target to build an object file
src/B1SteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1SteppingAction.cc.o
.PHONY : src/B1SteppingAction.cc.o

src/B1SteppingAction.i: src/B1SteppingAction.cc.i

.PHONY : src/B1SteppingAction.i

# target to preprocess a source file
src/B1SteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1SteppingAction.cc.i
.PHONY : src/B1SteppingAction.cc.i

src/B1SteppingAction.s: src/B1SteppingAction.cc.s

.PHONY : src/B1SteppingAction.s

# target to generate assembly for a file
src/B1SteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/Target_material.dir/build.make CMakeFiles/Target_material.dir/src/B1SteppingAction.cc.s
.PHONY : src/B1SteppingAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Target_material"
	@echo "... edit_cache"
	@echo "... Target_material.o"
	@echo "... Target_material.i"
	@echo "... Target_material.s"
	@echo "... src/B1ActionInitialization.o"
	@echo "... src/B1ActionInitialization.i"
	@echo "... src/B1ActionInitialization.s"
	@echo "... src/B1DetectorConstruction.o"
	@echo "... src/B1DetectorConstruction.i"
	@echo "... src/B1DetectorConstruction.s"
	@echo "... src/B1EventAction.o"
	@echo "... src/B1EventAction.i"
	@echo "... src/B1EventAction.s"
	@echo "... src/B1PrimaryGeneratorAction.o"
	@echo "... src/B1PrimaryGeneratorAction.i"
	@echo "... src/B1PrimaryGeneratorAction.s"
	@echo "... src/B1RunAction.o"
	@echo "... src/B1RunAction.i"
	@echo "... src/B1RunAction.s"
	@echo "... src/B1SteppingAction.o"
	@echo "... src/B1SteppingAction.i"
	@echo "... src/B1SteppingAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

